name: CI

on: [push, pull_request]

jobs:
  packages:
    name: Packages
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v2
      - run: python --version
      - run: sudo apt-get update
      - run: sudo apt-get install libxtst-dev libpng++-dev
      - run: sudo apt-get install build-essential
      - run: npm ci
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [packages]
    env:
      CI: true
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run package
  svelte-build:
    name: Svelte-Build
    runs-on: ubuntu-latest
    needs: [packages]
    env:
      CI: true
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run svelte-build
  typeCheck:
    name: Type Check
    runs-on: ubuntu-latest
    needs: [packages]
    env:
      CI: true
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run validate
